# Server configurations
server:
  host: "localhost"
  port: 8083


# databaseName credentials
databaseName:
  acawsDBName: "awacs"
  acawsSmartDBName: "awacs_smart"
  smartStockistDBName: "Smartstockist"

# databaseConfig credentials
databaseConfig:
  host: "localhost"
  port: 1434
  user: "appUser"
  pass: "Awacs123"

# Grpc configurations
grpcConfig:
  host: "127.0.0.1"
  port: 9000